### ISSUE TITLE
Cannot download alexNet__iter_60000.caffemodel 

### ISSUE THREAD

**Issue by nabiltkarim** [guoyilin/FaceDetection_CNN#9]
I went to website to download this file. But it stops downloading after 2mb every time. Any one know how to solve this?

**Comment by rykov8** [comment]
@ntkarim123 if you are a linux (mac) user try the following command (this is one-line command, markdown formats it weirdly):

`wget -c --referer=http://pan.baidu.com/s/1i38IAIp -O alexNet__iter_60000.caffemodel "http://87.245.198.80/ws.cdn.baidupcs.com/file/336..."`

You should copy/paste the direct link instead of `http://87.245.198.80/ws.cdn.baidupcs.com/file/336...` above, that appears during the browser downloading process.
I found this solution in some blog post, this is simply downloading the model weights via wget and some hacks how to to it from Baidu cloud. The downloading process is VERY slow, but it worked for me at least, hope, it will help you too.

**NB** You possibly need to install wget (e.g. on Ubuntu it is not pre-installed, but this is a very basic step)

**Comment by wajihullahbaig** [comment]
Hey guys, I guess Baidu removed the model. Can anyone share a link or upload it somehwere?
I have been trying to download using wget, but I keep getting unauthorized and page not found errors.

Any link is highly appreciated :)

**Comment by guoyilin** [comment]
https://pan.baidu.com/s/1pJJ2WKN

**Comment by guoyilin** [comment]
I upload ithe model in google drive: https://drive.google.com/file/d/0B8_dH3SiT7reMjJVRjJDXzJkRDQ/view?usp=sharing

**Comment by wajihullahbaig** [comment]
@guoyilin Thanks mate!!!
